### ISSUE TITLE
add blur/focus listening capabilities

### ISSUE THREAD

**Issue by Pomax** [i-like-robots/react-tags#103]
It would be rather useful to have onBlur and onFocus as props on the react-tags component so that parents can make decisions around whether to hanging input (text typed by the user but not yet interpreted as a tag) should be processed or not.

For example: a form with react-tags, user type "computer vision" and then clicks on "submit" rather than typing tab/enter first. With onBlur handling, the component that manages the full form can make an informed decision on whether or not to take the current string on board or ignore it before letting the form submission go through.

**Comment by i-like-robots** [comment]
Fixed in #102, thanks! Will be in 5.5 release.
