### ISSUE TITLE
handleFocus

### ISSUE THREAD

**Issue by yanniznik** [i-like-robots/react-tags#107]
Hi,

is handleFocus / handleBlur broken? I can't seem to make it trigger anything.

**Comment by i-like-robots** [comment]
Hi @yanniznik, do you have an example you can share of the behavior appearing to be broken?

**Comment by mysteryhistory** [comment]
I'm having the same problem. Can't trigger neither handleFocus nor handleBlur
Other handlers are working fine though

`<ReactTags
          tags={this.state.searchTerms}
          suggestions={suggestions}
          minQueryLength={1}
          allowNew={false}
          handleInputChange={this.handleSearchInputChange.bind(this)}
          handleDelete={this.handleDelete.bind(this)}
          handleAddition={this.handleAddition.bind(this)}
          handleBlur={() => {
            console.log('blur')
          }}
          handleFocus={() => {
            console.log('focus')
          }}
        />
`

Getting nothing in console.
Maybe you've found a solution, @yanniznik ? :)

**Comment by i-like-robots** [comment]
As I have had no further reports I am going to close this. Since the issue was reported there have also been several changes to event listeners, hopefully one of those fixed this problem for you.
