### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by bherila** [i-like-robots/react-tags#110]
Any thoughts about using [Typescript](http://www.typescriptlang.org/) to maintain quality and provide typings going forward? Happy to help with the migration if so, or could supply typing files to go along with the npm package.

Thanks,
Ben

**Comment by bherila** [comment]
note: This does not require users to use typescript, we'd publish the typescript compiled js files + typing files as the npm package. I might work on my own fork in the meanwhile :)

**Comment by i-like-robots** [comment]
Totally down for it! I personally love getting the typings come through in my editor, even if I'm not working on a TS project.

**Comment by nikola1970** [comment]
Are @types/react-tag-input compatible with this library? :)

**Comment by nikola1970** [comment]
@i-like-robots Are @types/react-tag-input compatible with this library? :)

**Comment by i-like-robots** [comment]
Somebody has kindly created typings for 5.x of this component, they are available here: https://www.npmjs.com/package/@types/react-tag-autocomplete

**Comment by i-like-robots** [comment]
Closing this now as I've decided that I'm not going to rewrite the library in TS and a decent types package has been created that I'm happy to help update.

**Comment by Stvad** [comment]
It seems the types package is outdate :(
