### ISSUE TITLE
React 16 support

### ISSUE THREAD

**Issue by amilajack** [i-like-robots/react-tags#113]
Does this module work with react 16? If so I'd love to bump the peerDeps of react and react-dom

**Comment by i-like-robots** [comment]
Yes it does - I've bumped in the V6 branch (https://github.com/i-like-robots/react-tags/pull/109/commits/afd26a1ba80568b53bcec88d4d6c106bc89a64b6) but not in master.

I'm aware there are a few projects still using V15 so perhaps it needs to be quite loose.

**Comment by GazzaHazza** [comment]
Could you maybe do this:
```
"peerDependencies": {
  "react": "^15.0.0 || ^16.0.0",
"react-dom": "^15.0.0 || ^16.0.0"
}
```
Would allow both R15 and R16?

**Comment by i-like-robots** [comment]
Yep, looks good - we did the same when we went from v0.14 to v15 😄

**Comment by i-like-robots** [comment]
I'm on a train at the moment so a PR would be greatly appreciated =]

**Comment by GazzaHazza** [comment]
Im not at my laptop so i cant either. I will in the morning!
