### ISSUE TITLE
Custom suggestions component and custom id and name keys

### ISSUE THREAD

**Issue by tjphopkins** [i-like-robots/react-tags#117]
I would like to add a few features to this library. Would you accept a PR with the following?:

1. 

**Custom id and name keys**:

- Prop for custom suggestions id key 
- Prop for custom suggestions name key (I believe this relates to issue https://github.com/i-like-robots/react-tags/issues/111)

e.g. to enable one to pass in a list of suggestions of the form:
{thisIdKey: <id>, thisnameKey: <name>} with customIdKey='thisIdKey' and customNameKey=thisNameKey. 

Currently you have to process your suggestions before passing them in as a prop, which has unnecessary performance implications.

2. 

**Custom suggestions component** prop, in the same vein as the tagComponent prop

Many thanks

**Comment by i-like-robots** [comment]
Added in #124

**Comment by designbyadrian** [comment]
Where did this go?

**Comment by i-like-robots** [comment]
@designbyadrian this feature was added to v6 which you can try out here: https://github.com/i-like-robots/react-tags/tree/6.0

**Comment by designbyadrian** [comment]
@i-like-robots Silly me! Being ignorant, I assumed the pull request for V6 in 2018 was the current version 😄 I shall try out the new version!
