### ISSUE TITLE
Scrollable suggestion dropdown, clicking the scroll bar causes the suggestions dropdown to collapse

### ISSUE THREAD

**Issue by nmoore93** [i-like-robots/react-tags#121]
Hi, thanks very much for the library!

I noticed a small issue when using this library when the suggestions list is given a max height and set to scroll when the number of suggestions would cause the height to go beyond this max height. Clicking the scroll bar would cause the suggestion list to collapse / disappear again as the event prevent default is only on the li elements in Suggestions.js

I have a simple fix ready to create a pull request where I add an event handler for the ul elements onmousedown which prevents the event from bubbling up.

Steps to recreate:

1. Update the suggestions ul styling to have overflows of scroll
2. Pass enough suggestions to cause the ul to be scrollable
3. Try to scroll the suggestions by clicking the scroll bar and dragging, rather than using a mouse wheel for example - the suggestions dropdown will close

Thanks

**Comment by i-like-robots** [comment]
Thanks for submitting such a detailed issue and accompanying PR @nmoore93 I'll take a look into it

**Comment by davidb-e4s** [comment]
Having this problem with Chrome in the latest version.

**Comment by s-nikhil** [comment]
@i-like-robots  Still having the same problem on latest version on chrome. Any other workaround except upgrading the library to the altest beta version?

**Comment by i-like-robots** [comment]
This issue has been resolved in [v7+](https://github.com/i-like-robots/react-tag-autocomplete)
