### ISSUE TITLE
Warning on Input Component

### ISSUE THREAD

**Issue by luciemac** [i-like-robots/react-tags#135]
I am having a warning using `ReactTags`:
```
Warning: Failed prop type: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    in input (created by Input)
    in div (created by Input)
    in Input (created by ReactTags)
    in div (created by ReactTags)
    in div (created by ReactTags)
```
From what is said [here](https://reactjs.org/docs/uncontrolled-components.html#default-values) we should probably change https://github.com/i-like-robots/react-tags/blob/master/lib/Input.js#L78 by something like:
`defaultValue={query}`

What do you think?
Thanks!

**Comment by gustavohornig** [comment]
I'm having the same issue, any suggestions?

**Comment by i-like-robots** [comment]
I'm afraid I've not seen this myself, could you let me know which React version you are using?

**Comment by luciemac** [comment]
I'm using React 16.3.2

**Comment by estherleah** [comment]
I am getting this problem when I use yarn instead on npm for package management.

**Comment by estherleah** [comment]
@i-like-robots I am also getting this problem.

**Comment by chellman** [comment]
I added a PR to change to defaultValue, but if you want a hack that avoids the warning until this is fixed, you can add a noop method to your class that uses ReactTags and reference it as the onChange for your component.  It's ugly, but it will stop the warnings.

```js
noOp() {
    // does nothing
}

<ReactTags
tags={this.state.tags}
suggestions={this.state.suggestions}
handleAddition={this.handleTagAddition}
handleDelete={this.handleTagDelete}
inputAttributes={{ onChange: this.noOp }}
/>
```

**Comment by i-like-robots** [comment]
This is an interesting issue, it was discussed at length some years back in https://github.com/facebook/react/issues/1118 (although I've never seen this warning, with any version of React including 16.3.2!)

There is nothing wrong with the current implementation but I agree any warnings cluttering up the console are annoying and to be avoided. 

I'm not sure that setting `defaultValue` is the right solution as it may have unintended consequences (https://github.com/i-like-robots/react-tags/pull/139#issuecomment-431006214) but there are potentially several other workarounds.

**Comment by i-like-robots** [comment]
Looking into this some more I can see that this warning has 5 conditions:

https://github.com/facebook/react/blob/b87aabdfe1b7461e7331abb3601d9e6bb27544bc/packages/react-dom/src/shared/ReactControlledValuePropTypes.js#L32-L46

It is the first condition which interests because by default this _should_ evaluate to `true` causing the to return early and output no warning.
