### ISSUE TITLE
addOnBlur prop

### ISSUE THREAD

**Issue by APILLSBURY** [i-like-robots/react-tags#136]
For my use case I'd like to be able to add a tag onBlur (if there's a query). I forked the repo and made a patch that exposes an addOnBlur prop, but I'd like to also issue an upstream PR. However, I'm not sure whether I should issue it against master or against the 6.0 branch. Can you give me some guidance on that?

**Comment by i-like-robots** [comment]
Hello @APILLSBURY, thanks for your question. I think it would be easiest to raise a PR against the master branch because I don't know when 6.0 will be finished...

Could you clarify what the difference is between this and using the existing `handleBlur` callback to create the same functionality?

**Comment by APILLSBURY** [comment]
@i-like-robots The problem with `handleBlur` is that it doesn't give access to the query. While you can use `handleInputChange` to keep track of what the current query is, if you want to add it on blur there's no way to clear it out, so you end up adding a tag while the query remains the same as before.

**Comment by APILLSBURY** [comment]
I opened https://github.com/i-like-robots/react-tags/pull/138

**Comment by i-like-robots** [comment]
Released [5.7.0](https://github.com/i-like-robots/react-tags/releases/tag/v5.7.0)
