### ISSUE TITLE
Key presses no longer add a tag

### ISSUE THREAD

**Issue by noobling** [i-like-robots/react-tags#143]
I suspect the `event.keyCode` has been deprecated on newer browsers so it no longer works. I will investigate further today and make a PR if this is the case.

**Comment by noobling** [comment]
After reading the code it appears I had fallen into the trap of not setting `allowNew` prop this seems like a common pitfall to new users perhaps we should make it more apparent in the docs?

**Comment by kosmakoff** [comment]
Lol, just got into same problem. I believe this option should be `on` by default.
