### ISSUE TITLE
Maximum depth exceeded error occurs when adding tags too fast

### ISSUE THREAD

**Issue by Fanni1993** [i-like-robots/react-tags#146]
Scenario: We used ReactTags component with autoresize. When we add many tags after each other in a small amount of time, the whole application crashes with the error above. 

We made a new branch where we created a new sizer test: 'resizes input to match random sizer width'.  Earlier sizer.scrollWidth's value was always 0 in tests this is why the test never failed. Now scrollWidth is a random whole number, and we able to reproduce the error. 

The problem is calling setState too many times in ComponentDidUpdate(). Our quick solution was to move out inputWidth from state, and modify updateInputWidth() to return inputWidth instead of call setState. We had to increase the number added to scrollWidth from +2 to more. (We used +20 but this was an arbitrary number and we are not sure how to calculate this better.) We would appreciate if you take a look at the issue and share your thoughts about the solution. 

Branch with new test and quickfix: https://github.com/i-like-robots/react-tags/pull/145

**Comment by i-like-robots** [comment]
Thanks for reporting this @Fanni1993. I think it makes sense, refamiliarising myself with the code I can see that the `componentDidUpdate()` hook immediately calls another update...

Is there a reliable way to recreate this error?

The original implementation was based upon https://github.com/JedWatson/react-input-autosize which I assume has better safeguards against this so I'll have a look at that too.

**Comment by Fanni1993** [comment]
Hello!

Is there any update on this topic?
Thank you!

**Comment by i-like-robots** [comment]
I have tried to recreate this issue and spoken to several users of this component but I have not seen nor heard about this issue from anybody else to investigate it any further. I also spent some time analysing other React components which have similar resizing functionality to confirm if their implementation had extra safeguards this component did not have but I did not find anything new.

I did experiment with adding some extra checks and removing the unnecessary `componentWillReceiveProps()` method ([in this branch](https://github.com/i-like-robots/react-tags/compare/master...i-like-robots:fix-recursive-set-width)) but without being able to recreate the issue I'm just guessing.

Are you OK to share your implementation with me or create an isolated test case?

**Comment by prashantpatil14** [comment]
Hello!

I found same issue with Browser specific , in Chrome browser its working fine, but issue with firefox and safari browser :

_> Unhandled Rejection (Invariant Violation): Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops._

"react-dom": "^16.4.2",
"node -v": "v8.12.0",
"npm -v: : "6.13.4",

its crash in handleInputChange function.

**Comment by i-like-robots** [comment]
Hi @prashantpatil14  - are you able to share an example which demonstrates this problem?

**Comment by i-like-robots** [comment]
I've added a guard condition to the `componentDidUpdate()` callback implemented by the `<Input />` component: https://github.com/i-like-robots/react-tags/commit/2d798f17c4965a10c12c5069e5191967f0a29530

This is to match advice from the React docs:

> You may call `setState()` immediately in `componentDidUpdate()` but note that it must be wrapped in a condition like in the example above, or you’ll cause an infinite loop.

I've not been able to recreate this issue myself, or seen it with my own eyes, so I can't be sure if this change will fix this for you but if you try it out please do let me know if it resolves the problem.

**Comment by i-like-robots** [comment]
I've released v5.12.1 with a provisional fix for this issue and will release a v6.0.0-beta.4 in due course. I'm going to close this issue now but please do add any further information if you have any.
