### ISSUE TITLE
Enhancement - Prevent Duplicates

### ISSUE THREAD

**Issue by claybanks1989** [i-like-robots/react-tags#148]
Not sure if this is the right place for enhancement requests, but It would be great if you could implement "Prevent Duplicates" as an option so that users cannot enter the same tag twice. I know it could be handled in the `handleAddition` method but it'd be a useful feature to have out of the box

**Comment by i-like-robots** [comment]
Hi @claybanks1989 thanks for your suggestion.

You're right in suggesting that this can be handled by `handleAddition` and there is also a  `handleValidate` callback that could be used implement this functionality.

**Comment by musman92** [comment]
it did not work because suggestions still showing that value, 
this is how i work around for that.

`
...
 handleDelete (i) {
    const tags = this.state.tags.slice(0)
   // on del push into suggestion's array
    const suggestions = this.state.suggestions
    suggestions.push(tags[i])
    tags.splice(i, 1)
    this.setState({ tags, suggestions  })
  }
...
 handleAddition (tag) {
// remove selection from suggestion list
    const suggestions = this.state.suggestions .slice(0)
   const i = this.state.suggestions.indexOf(tag)
   suggestions.splice(i, 1)

    const tags = [].concat(this.state.tags, tag)
    this.setState({ tags, suggestions })
  }
...
`

**Comment by i-like-robots** [comment]
Please note that in your code you are mutating an array with `.push()` in `handleDelete()`, you may want to clone the suggestions array first (e.g. `.slice(0)` or `[].concat(oldArray)`).

> Never mutate this.state directly, as calling setState() afterwards may replace the mutation you made. Treat this.state as if it were immutable.
> - https://reactjs.org/docs/react-component.html
