### ISSUE TITLE
Can't remove tags added.

### ISSUE THREAD

**Issue by AlexCryptoStar** [i-like-robots/react-tags#149]
I can't remove the selected tag because it appears to add the tag but continue to call the handleAddition () method without calling the handleDelete () method.
![2019-03-08-12-03-dev5 edr to](https://user-images.githubusercontent.com/43492549/54004937-7e35da80-4192-11e9-98e4-a60993675a2e.png)

**Comment by i-like-robots** [comment]
Hi @AlexCryptoStar are you able to share your source code or a demo of this issue?

**Comment by i-like-robots** [comment]
I'm closing this as no new information has been added.
