### ISSUE TITLE
Option to display tags on the right

### ISSUE THREAD

**Issue by Noollab** [i-like-robots/react-tags#163]
It would be really nice to have the option of showing selected tags to the right of the input field and thus having it remain stationary (while tags expand outwards)

**Comment by i-like-robots** [comment]
This is straightforward to achieve with CSS by updating the styles to make the top-level element  a flex container and adding an order to the selected tags element, as shown below:

<img width="1440" alt="Screenshot 2019-10-12 at 13 14 03" src="https://user-images.githubusercontent.com/271645/66701254-36f86500-ecf2-11e9-8ec8-9499bdcfd318.png">
