### ISSUE TITLE
Options to support hiding placeholder if there is any selected tag

### ISSUE THREAD

**Issue by theJian** [i-like-robots/react-tags#165]
react tags version: 6 beta.0

`placeholderText` won't be hidden when there are selected tags. The workaround is passing an empty string if there is any selected tag.
```JavaScript
placeholderText={tags.length ? '' : 'placeholder'}
```
 I propose that `placeholderText` can be renamed to `placeholderSearchText` because it's actually the placeholder of search input, and the new `placeholderText` will work exactly like the placeholder of React Tags, it only appears when there is no selected tag.

**Comment by i-like-robots** [comment]
Thanks for your suggestion @theJian - your current workaround seems quite neat to me as it achieves what you want with minimal code, I'm not sure changing the library could really improve upon it!
