### ISSUE TITLE
Pass query to suggestionsFilter as parameter

### ISSUE THREAD

**Issue by theJian** [i-like-robots/react-tags#166]
It would be handy when you need to filter suggestions according to query using some custom rules.
We can add query as the second argument so that it's still compatible with the old version.

**Comment by i-like-robots** [comment]
This feature was released in 5.11, details are here: https://github.com/i-like-robots/react-tags/blob/master/CHANGELOG.md#5110

**Comment by theJian** [comment]
Is it still available on version 6?

https://github.com/i-like-robots/react-tags/blob/6.0/lib/ReactTags.js#L78

**Comment by i-like-robots** [comment]
I'll merge master into that branch and release as `6.0.0-beta.1`

**Comment by i-like-robots** [comment]
Version 6.0.0-beta.1 is not available on npm
