### ISSUE TITLE
Special regex characters need escaping in query

### ISSUE THREAD

**Issue by jaweesner** [i-like-robots/react-tags#169]
Currently, in order to check if the user entered in an exact match to an existing suggestion, the query is used to generate a regex. However,  the string is not escaped, so if the query entered has regex special characters in it that would cause the regex to be invalid, the regex constructor throws an error. 

For example, if the  user enters "(B" as their query, the value fed to the RegExp constructor is "^(B$", which throws a  
```Invalid regular expression: /^(B$/: Unterminated group``` unhandled exception

Pertinent code line: 
https://github.com/i-like-robots/react-tags/blob/2921df905f244eeb7484f032718a6a9c72a59638/lib/ReactTags.js#L111
```
if (query.length >= this.props.minQueryLength) {
   // Check if the user typed in an existing suggestion.
   var match = this.suggestions.state.options.findIndex(function (suggestion) {
   return suggestion.name.search(new RegExp("^" + query + "$", 'i')) === 0;
   });
```

**Comment by i-like-robots** [comment]
Thanks for the report @jaweesner

A utility does already exist within the component to escape the query when creating RegExps but I think if it may be simpler to check the equality of the values instead...

Would you be willing to submit a PR for this?

**Comment by i-like-robots** [comment]
This may also already be fixed in the v6 release as the query is being escaped:

https://github.com/i-like-robots/react-tags/blob/6.0/lib/concerns/matchers.js#L13-L15

**Comment by jaweesner** [comment]
@i-like-robots  nice! I'll check out v6 later today to confirm the issue I'm seeing is complete (and close ticket if it is)

**Comment by i-like-robots** [comment]
Closing this as I believe the issue as I've had no further reports.
