### ISSUE TITLE
Suggestion: rename repo or npm module

### ISSUE THREAD

**Issue by heymartinadams** [i-like-robots/react-tags#170]
Excellent OSS! Thank you 👍 

May I make a suggestion that you either rename the NPM package to the name of this repo `react-tags`, or rename this repo to the name of the NPM package `react-tag-autocomplete`?

Makes things a bit less confusing. No biggie, though.

Again, great work ✨

**Comment by i-like-robots** [comment]
Thank you for your comments 😄 

I think renaming the repo is a good idea and as I recently requested it to be "unforked" from the original project (they have diverged so far apart) that is now possible.

**Comment by i-like-robots** [comment]
The [next major version](https://github.com/i-like-robots/react-tag-autocomplete) of this component is now in a new repo using the same name as the npm package.
