### ISSUE TITLE
New Line/Line breaks as delimitter

### ISSUE THREAD

**Issue by cakerake** [i-like-robots/react-tags#176]
I'm trying to configure copy paste support for documents with one tag per line, so far i can't find a way to make that work.

Is there a way to get linebreak or newline delimitter support?

**Comment by i-like-robots** [comment]
There has been previous discussion about adding support for copy and pasting but the conclusion was that attempting to provide a solution out of the box makes the two uses of this component (with `allowNew` enabled or disabled) too difficult to reconcile (see https://github.com/i-like-robots/react-tags/issues/84#issuecomment-333398346).

The `handleInputChange` in v5 or `onInput` in v6 callbacks should provide a mechanism to hook in and introduce the functionality you're after. If you do decide to do this I'd love to see the outcome!
