### ISSUE TITLE
Suggestion: provide a link to a live demo

### ISSUE THREAD

**Issue by fotoflo** [i-like-robots/react-tags#178]
As a developer new to this component, i want to see what i'm going to get when working with it... a live demo would be great for that.  Thanks

**Comment by i-like-robots** [comment]
Hello, there is a link at the top of repository page: http://i-like-robots.github.io/react-tags/

**Comment by zhouhao27** [comment]
Can you provide source code for http://i-like-robots.github.io/react-tags/? Thanks.

**Comment by i-like-robots** [comment]
It's the output of the `/example` directory here: https://github.com/i-like-robots/react-tags/tree/master/example

**Comment by zhouhao27** [comment]
Thanks. I think I missed the css. It works fine when I add this line to my code:

`import './style.css'`
