### ISSUE TITLE
Multiple Instances?

### ISSUE THREAD

**Issue by ellunium** [i-like-robots/react-tags#179]
Sorry to ask such a newbie question, but, what's the best way to have multiple instances sharing the same validation methods?

**Comment by jacekk** [comment]
@ellunium Does the attached example address your question?

[![Edit nice-morning-s4dgr](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/nice-morning-s4dgr?fontsize=14&hidenavigation=1&theme=dark)

**Comment by ellunium** [comment]
Hi @jacekk,

Thanks for the example.

It comes close, but I wanted to share the validation function among all the reacttags.

Since some built-in functions don’t pass the event, to get the event.target, I guess the best approach would be with refs or classNames.

Thanks for sharing though :)

**Comment by jacekk** [comment]
@ellunium 

> It comes close, but I wanted to share the validation function among all the reacttags.

You could create a `CustomReactTags` component with your validation, addition, deletion logic and use it throughout your applications. That would be **shared** among **all** instances. I usually do that as I want certain external library to look&feel my way.

**Comment by jacekk** [comment]
@ellunium 

> Since some built-in functions don’t pass the event, to get the event.target, I guess the best approach would be with refs or classNames.

I am not exactly sure why you need `event` objects. This library gives a nice abstraction and simplifies everything. `handleAddition` and `handleDeletion` cover like 99% percent of use cases which do not need exposing `event` nor `target`. At least, that was the idea :)

**Comment by ellunium** [comment]
> @ellunium
> 
> > It comes close, but I wanted to share the validation function among all the reacttags.
> 
> You could create a `CustomReactTags` component with your validation, addition, deletion logic and use it throughout your applications. That would be **shared** among **all** instances. I usually do that as I want certain external library to look&feel my way.

Never thought of that! Thanks for sharing, I’ll give it a try :)
