### ISSUE TITLE
onInput: How to popup suggestions immediately?

### ISSUE THREAD

**Issue by derwaldgeist** [i-like-robots/react-tags#187]
I am using `onInput`  to retrieve suggestions dynamically. In principle, this works. I type a character, the new suggestions are retrieved and populated. Unfortunately, they do not show up immediately, but only after I type another character. Is there a way to open the suggestions as soon as they are updated?

I tried to return a Promise in addition to just setting the new suggestions as a state property, but this did not help.

**Comment by i-like-robots** [comment]
If you are able to share your integration I'd be happy to have a look at it. I have previously used (an old version of) the component as you describe.

**Comment by derwaldgeist** [comment]
No, I lived with it for now.

**Comment by hsaleem11** [comment]
I see, I've been debugging this for a while without any progress. I may have to use a different library altogether

**Comment by hsaleem11** [comment]
Just wanted to update you guys on this, but I managed to get this working by loading all of the data on page load. Now I'm able to see all items on first key press. This might not be a good idea if you expect to deal with large amounts of data since this could increase the page loading time, but it's good enough for my use case. Basically, I set ```minQueryLength = 1``` and made the api call inside ```componentDidMount()```, and then updated the state variable I was using.

**Comment by i-like-robots** [comment]
Thank you for your update @hsaleem11, I'm glad you have found a reasonable solution.

I have just spent a few minutes messing with the example to make it fetch suggestions from a remote source, you can see this code here: https://github.com/i-like-robots/react-tags/compare/async-fetch-example

This is working for me as expected:

![breweries](https://user-images.githubusercontent.com/271645/79787080-51189d00-833e-11ea-91d5-a0c37dec7996.gif)

**Comment by hsaleem11** [comment]
Thanks for the example, it's very helpful. I'll be sure to reference this example in the future if I need it!

**Comment by i-like-robots** [comment]
Closing this now as I believe no changes to the component are required.
