### ISSUE TITLE
allowUnique option is not available

### ISSUE THREAD

**Issue by NileshTops** [i-like-robots/react-tags#191]
Let me know how can i prevent duplication of items.

**Comment by i-like-robots** [comment]
If you're referring to suggestions then you will need to filter them before passing them into the component.

To avoid duplicate selected tags you can use the validate callback: https://github.com/i-like-robots/react-tags#handlevalidate-optional

**Comment by NileshTops** [comment]
Thanks

**Comment by timrobinson33** [comment]
This is a good workaround but it would be great to have some kind of "disallow duplicates" option that stops the existing ones even showing up in the list of suggestions. I would imagine that 90% of the time this is what you would want
