### ISSUE TITLE
Scroll active suggestion into view

### ISSUE THREAD

**Issue by willsmanley** [i-like-robots/react-tags#194]
I am overriding the `maxSuggestionsLength` prop to 1000 and my suggestions are in a scrollable div.

When I use the arrow keys to navigate between the suggestions, I would like to be able to keep the active suggestion in view.

Since the package doesn't expose a ref for the `suggestionComponent`, is there any way to handle scrolling in this way?

**Comment by sibiraj-s** [comment]
I am not sure about the use case though. will something like #214 fix your problem, You should be able to render the best matched suggestion(s) to be near the component and may be you don't need scroll?

**Comment by i-like-robots** [comment]
The highlighted suggestion is automatically scrolled into view in the [next major version](https://github.com/i-like-robots/react-tag-autocomplete) of the component.

**Comment by i-like-robots** [comment]
This behaviour is available in [v7+](https://github.com/i-like-robots/react-tag-autocomplete)
