### ISSUE TITLE
Clicking anywhere on a tag deletes it.

### ISSUE THREAD

**Issue by Shelagh-Lewins** [i-like-robots/react-tags#197]
When you look at a tag, it has an 'x' button at the right which I expect to delete the tag.

What I don't expect is that clicking outside the 'x', anywhere on the tag text, deletes the tag. And since I wasn't expecting it, I likely don't remember what the tag text was so can't recreate it.

I expect clicking the tag text to either do nothing, or highlight the tag (and then pressing 'delete' on the keyboard would remove it)

You can see this on the demo:

http://i-like-robots.github.io/react-tags/

I think it's poor usability to delete something unexpectedly and without the option to cancel.

I think the tag should only be deleted if you click the 'x', not if you just click the text.

**Comment by i-like-robots** [comment]
If the default behaviour is not what you want it's possible to provide your own tag component using the [`tagComponent`](https://github.com/i-like-robots/react-tags#tagcomponent-optional) prop. Here's an example:

```jsx
const tagComponent = ({ tag, onDelete }) => {
  return <div>{tag.name} <button onClick={onDelete}>Remove Tag</button></div>
}
```

**Comment by Shelagh-Lewins** [comment]
Nice! Thank you, I will check that out.
