### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by creativiii** [i-like-robots/react-tags#200]
I can't seem to create tags. I can type in the input just fine, but nothing will create a tag. I've tried, tab, return, comma, full stop, anything immaginable.

I've tested this on Ubuntu, Android and iPhone. 

I'm currently getting no console logs whatsoever. This is happening both on my local project as well as with the [Demo](http://i-like-robots.github.io/react-tags/). 

## Steps to Reproduce

Steps to reproduce the problem:

1. Go to the example
2. Type something
3. Press comma, enter or tab
4. Tag doesn't get created and state doesn't change

## My environment

 - OS: [e.g. Windows 10] Ubuntu 20.04, Android 10, iOS 13
 - Browser: [e.g. chrome 76, safari 12] Chrome, Firefox Safari
 - Version of the component: [e.g. 5.11.2] 5 and 6

Any idea what's going on? I've used this component before with no problems

**Comment by i-like-robots** [comment]
Everything seems to working as expected for me on my laptop and phone. Nothing has changed for a little while so I'm not sure what you're experiencing. Please note that the demo has the `allowNew` option disabled and you must select a country from the list.

**Comment by creativiii** [comment]
I'm not even getting any suggestions for some reason. The suggestions should just appear as I type right?

**Comment by creativiii** [comment]
> Everything seems to working as expected for me on my laptop and phone. Nothing has changed for a little while so I'm not sure what you're experiencing. Please note that the demo has the `allowNew` option disabled and you must select a country from the list.

You're right, that's the problem I was having with the Demo sorry about that. I guess I'll try to figure out what the problem is locally.

Will post if I figure it out.
