### ISSUE TITLE
Allow inputAttributes to override existing attributes

### ISSUE THREAD

**Issue by Herdismaria** [i-like-robots/react-tags#202]
## Describe the solution you'd like
We can already add attributes to the input via the inputAttributes props. However it would be nice if we could override all/some of the existing attributes. For example the aria-label. Now it uses the placeholder but sometimes the placeholder is just a hint and not clear enough for users using screen readers.

I want to be able to override the aria-label.

**Comment by i-like-robots** [comment]
You've raised an interesting point @Herdismaria - placeholders serve a different purpose to labels and are not equivelent. Perhaps adding a new `label` option (which could also output a `<label>` element?) would be useful addition.

**Comment by Herdismaria** [comment]
Label could work and would be a nice addition. However some use cases don't involve a label so it would need to be optional and allow some custom styling, I guess. 
The simples solution to the aria-label problem would probably be to just add a prop for it, make it optional and default to the label/placeholder?

**Comment by i-like-robots** [comment]
Sounds good to me. Are you happy to submit a PR for this?
