### ISSUE TITLE
Add a 'required' prop so that the text-field can be used with HTML5 form validation

### ISSUE THREAD

**Issue by azhuologist** [i-like-robots/react-tags#204]
## Describe the solution you'd like

This way, users putting the component in HTML `form` attributes can ensure something has been entered by leveraging HTML5 form validation. The `required` prop would be passed as an attribute into the `input` element.

**Comment by i-like-robots** [comment]
A `required` attribute can be added to the input via the existing [`inputAttributes`](https://github.com/i-like-robots/react-tags#inputAttributes-optional) options.

Any further validation (e.g. > 0 tags have been selected) should be implemented by the consumer.

**Comment by azhuologist** [comment]
Ah, I didn't notice that option. Resolved, thanks!
