### ISSUE TITLE
Server-side autocomplete example?

### ISSUE THREAD

**Issue by yrik** [i-like-robots/react-tags#205]

**Comment by i-like-robots** [comment]
Luckily enough, I did this a few days ago 😄: https://github.com/i-like-robots/react-tags/compare/v5.13.0...async-fetch-example

**Comment by sauldeleon** [comment]
yay!, just looking for this!

**Comment by sauldeleon** [comment]
example with axios and hooks:

```
  //initial api call
  const [{ data: labelsData }, doGetLabels] = useAxios({
    url: '/labels',
  })
  
  const [busy, setBusy] = useState(false)
  const handleInputChange = debounce((name) => {
    if (!busy) {
      setBusy(true)
      doGetLabels({ params: { name } })
    }
  })
  //getResponseData is my custom parser for the BE response
  useEffect(() => {
    const labels = labelsData ? getResponseData(labelsData).labels : []
    if (setBusy) {
      setBusy(false)
    }
    setSuggestions(labels)
  }, [labelsData])
```

Rest of the code remains the same as the @i-like-robots PR

**Comment by yrik** [comment]
Thanks for the example, seems like there is a small issue.
The options list is updated directly after the `onInput` custom handler.
However, when I query the server there it takes some time.
In a result, the options list always contains list of suggestions from previous call, not the latest one.
https://github.com/i-like-robots/react-tags/blob/6.0/lib/ReactTags.js#L130
