### ISSUE TITLE
React Tags ignores suggestions unless it matches from the first character

### ISSUE THREAD

**Issue by muyiwaoyeniyi** [i-like-robots/react-tags#215]
Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

## Expected behaviour
All suggestions should be rendered regardless of if the match was from the first character.

## Current behaviour
If you search for a tag and the suggestions don't start with that text, suggestions are not rendered. Though it seems for work for each word in the text.

## Example and screenshots
![screenshot1](https://user-images.githubusercontent.com/1622600/88465131-85947b80-ce8e-11ea-881a-380f38c47af1.png)
![screenshot2](https://user-images.githubusercontent.com/1622600/88465133-87f6d580-ce8e-11ea-920f-7cc0692fa846.png)
![screenshot3](https://user-images.githubusercontent.com/1622600/88465135-8a592f80-ce8e-11ea-9080-492579b50563.png)

## Your environment

 - OS: Ubuntu 18.04
 - Browser: Chrome 84
 - Version of the component: 6.0.0
 - React version: 16.9.0

**Comment by i-like-robots** [comment]
The default suggestions filter can be overridden using the [`suggestionsFilter`](https://github.com/i-like-robots/react-tags#suggestionsfilter-optional) option.

**Comment by muyiwaoyeniyi** [comment]
@i-like-robots That worked. I simply sent in a function that returned true and it matched/highlighted correctly. 

`const suggestionsFilter = () => true;`

Thanks!

**Comment by i-like-robots** [comment]
Glad your problem is sorted 👍

**Comment by muyiwaoyeniyi** [comment]
Thanks!
