### ISSUE TITLE
Support Chinese search？

### ISSUE THREAD

**Issue by tibic** [i-like-robots/react-tags#231]
可以支持中文搜索吗？可以支持中文吗？可以支持中文吗？

**Comment by i-like-robots** [comment]
I'm not sure. The suggestions filter can be overridden using the [`suggestionsFilter`](https://github.com/i-like-robots/react-tags#suggestionsfilter-optional) option but I don't know what other changes would be needed for the component to work well with non-ASCII characters.

**Comment by tibic** [comment]
Chinese characters placed before the suggested options can be matched, but you need to type two characters

**Comment by tibic** [comment]
That's what I do now
