### ISSUE TITLE
Add a disabled prop

### ISSUE THREAD

**Issue by jklingen92** [i-like-robots/react-tags#238]
## Describe the solution you'd like
Add a prop that freezes all input and tag deletion

## Describe alternatives you've considered
This is pretty standard functionality for input fields.

## Additional context

**Comment by i-like-robots** [comment]
This sounds like a useful feature and I'd be happy to accept a PR to add it 😃

**Comment by i-like-robots** [comment]
I have added an `isDisabled` prop to the v7 version of this component currently in development here: https://github.com/i-like-robots/react-tag-autocomplete/

**Comment by i-like-robots** [comment]
Closing as v7 has now been released and disabling the component is now a supported featue.
