### ISSUE TITLE
Any easy way to display the full list of suggestions when user focus on the input?

### ISSUE THREAD

**Issue by juanlet** [i-like-robots/react-tags#240]
I would like to display the list of suggestions when the user focus on the input to make it more intuitive to users who don't know the options. I haven't found a way of displaying the suggestion list on the docs, any way to do this?

**Comment by i-like-robots** [comment]
Setting [`minQueryLength`](https://github.com/i-like-robots/react-tags#minquerylength-optional) to zero will show the suggestions on focus.
