### ISSUE TITLE
Amazing component. Bravo 👏🏼 

### ISSUE THREAD

**Issue by acelaya** [i-like-robots/react-tags#243]
I just wanted to say that 🙂 

I was using another "tags component" on a project, but it was no longer maintained since around 3 years ago.

Looking for alternatives I ended up here, and it was super easy to migrate to this component, and to get it customized to nicely fit with the project's UI.

The resulting code was even simpler than the one I had before, as this component abstracts all the complexities in a very nice way.

Congratulations 🙂

**Comment by i-like-robots** [comment]
Thank you, much appreciated
