### ISSUE TITLE
Does not support numeric value if it is brackets

### ISSUE THREAD

**Issue by sandyksit** [i-like-robots/react-tags#248]
Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

## Expected behaviour
It should search any text and numeric 

## Current behaviour
As per current behavior its searching only text its not searching numeric if its in brackets(1234)

## Steps to Reproduce

Steps to reproduce the problem:

1.  put item in the list like 'name (1234)
2. start search like 1234 
3. its not searching the tag
4. its searching only when use brackets with number

## Your environment

 - OS: [e.g. Windows 10]
 - Browser: [e.g. chrome 76, safari 12]
 - Version of the component: [e.g. 5.11.2]
 - React version: [e.g. 16.12]

## Additional context

Add any other useful context about the problem here.

**Comment by i-like-robots** [comment]
You may use the [`suggestionsFilter`](https://github.com/i-like-robots/react-tags#suggestionsfilter-optional) or [`suggestionsTransform`](https://github.com/i-like-robots/react-tags#suggestionstransform-optional) props to replace the partial match pattern or filtering logic. 

The default pattern is [here](https://github.com/i-like-robots/react-tags/blob/main/lib/concerns/matchers.js#L9-L11) - if you find a pattern that suits you I'd be happy to accept a PR updating it 🙂
