### ISSUE TITLE
Option to remove maxSuggestionsLength

### ISSUE THREAD

**Issue by phiter** [i-like-robots/react-tags#251]
## Describe the solution you'd like

There should be a way to remove `maxSuggestionsLength` and make it infinite. I tried using `-1` but it doesn't work.

## Describe alternatives you've considered

I suppose we could make it nullable since `undefined` gives a default value of 6.

**Comment by i-like-robots** [comment]
Have you tried setting the `maxSuggestionsLength` prop to `Infinity`? This should do what you want.

**Comment by phiter** [comment]
That makes more sense. Will try that.
