### ISSUE TITLE
In the online demo you can't create a tag with spaces

### ISSUE THREAD

**Issue by herrKlein** [i-like-robots/react-tags#254]
The online demo does not allow tags with space to be created, although the option is shown
http://i-like-robots.github.io/react-tags/

## Expected behaviour

If it should be possible to create a tag with space, it should be created.
If not, user should be warned ( or at least not show the option, 'create tag:' )

## Current behaviour

Option create tag is show, does nothing

## Steps to Reproduce

Steps to reproduce the problem:

1. http://i-like-robots.github.io/react-tags/ 
2. go to custom tag input
3. enter text like 'abc 123'
4. press create tag option
5. no feedback

 - OS: OSX
 - Browser: chrome 94
 - Version of the component: online version
 - React version: online version

**Comment by i-like-robots** [comment]
I've been reviewing the accessibility of this component recently and I am working on a feedback mechanism, I believe this would fit nicely within that piece of work.

**Comment by i-like-robots** [comment]
The [next major version](https://github.com/i-like-robots/react-tag-autocomplete) of the component now supports displaying an invalid state with relevant attributes for associating the component with error messages.

**Comment by i-like-robots** [comment]
Support for an invalid state is available in [v7+](https://github.com/i-like-robots/react-tag-autocomplete)
