### ISSUE TITLE
In the online demo notifying failure status on creation

### ISSUE THREAD

**Issue by kabilanvennila** [i-like-robots/react-tags#256]
## Describe the solution you'd like

Having a little notification While utilising the Online Demo that lets the user know if creation fails with a small red signal or a small Flying Notification

## Additional context

While trying to create a new custom tag it says create anything that i type even if it doesn't meet the requirements such as more than 3 characters and clicking on it really doesn't do anything

**Comment by i-like-robots** [comment]
I have added a notification to the examples in the upcoming major release of this component: https://i-like-robots.github.io/react-tag-autocomplete/
