### ISSUE TITLE
make TagComponent props customizable i.e. enable adding more properties than just id & name.

### ISSUE THREAD

**Issue by tacmoktan** [i-like-robots/react-tags#259]

**Comment by tacmoktan** [comment]
Looks like Sebastian here got it done.

**Comment by i-like-robots** [comment]
Thanks for your contribution, I'm happy to add this.

This is also the behaviour of next major version of the component which will be in beta soon: https://github.com/i-like-robots/react-tag-autocomplete/

**Comment by i-like-robots** [comment]
Closing as v7 has now been released and appending additional properties to tags is supported.
