### ISSUE TITLE
Autoresize causes input to jump around

### ISSUE THREAD

**Issue by jtojnar** [i-like-robots/react-tags#261]
## Current behaviour

When the placeholder does not fit on first line, it is placed on another one. But when one starts typing, the input will shrink, which might make it fit on the first line again.

## Expected behaviour

The input should not shrink to be shorter than placeholder.

## Steps to Reproduce

Steps to reproduce the problem:

1. Add tags until placeholder would not fit.
2. Type.

## Example

Can reproduce it on the [demo](http://i-like-robots.github.io/react-tags/) too.

## Screenshots

https://user-images.githubusercontent.com/705123/150530888-41630ceb-3edd-4e73-8fca-1b8d5f0ea4de.mp4

## Your environment

 - OS: NixOS
 - Browser: Firefox 96.0.1, Chromium too.
 - Version of the component: 6.3.0
 - React version: 17.0.2

**Comment by i-like-robots** [comment]
This is now the default behaviour in [the next major version of this component](https://github.com/i-like-robots/react-tag-autocomplete)

**Comment by i-like-robots** [comment]
Closing as v7 has now been released and the input will no longer render narrower than the placeholder text.

**Comment by jtojnar** [comment]
Thanks. But it looks like there is still some pathological case in `InputSizer`:

[Screencast from 2023-07-16 17-03-38.webm](https://github.com/i-like-robots/react-tags/assets/705123/967391ee-f00a-461e-986e-f805150461a8)

Will try to debug it closer next week.
