### ISSUE TITLE
Label causing first item to be deleted.

### ISSUE THREAD

**Issue by dasveloper** [i-like-robots/react-tags#263]
When adding a label to the ReactTags input, it is causing the first tag to be deleted on focus.

## Expected behaviour
Clicking the label should focus the input.

## Current behaviour
Clicking the label focuses the first tag, triggering the onDelete function and removing it.

## Steps to Reproduce

Steps to reproduce the problem:

1. Create a fresh react app (npx create-react-app demo)
2. Install react-tag-autocomplete
3. Add label around your ReactTags component (like in code snippet below)
5. Add a few tags to your input
6. Click the label, you'll see a tag dissappear

```
<label>
  My label 
  <ReactTags
    allowNew
    tags={tags}
    onDelete={onDelete}
    onAddition={onAddition}
  />
</label>
```

## Example and screenshots
https://github.com/dasveloper/demo-react-tags

## Your environment

 - OS: macOS Monterey
 - Browser: chrome v101
 - Version of the component: 6.3.0
 - React version: 18.1.0

## Additional context

I believe just allowing an ID to be added to the input itself, so we can add an `htmlFor` attribute to the label would make it focus the input instead of the first tag.

**Comment by i-like-robots** [comment]
Thanks for taking the time to submit this issue.

Your suggestion of adding an ID is actually possible, you can append an ID using the [`inputAttributes`](https://github.com/i-like-robots/react-tags#inputAttributes-optional) prop.

In terms of how your example code should behave... well, I don't know, wrapping the whole component in a label is not something I'd recommend. According to [the HTML spec](https://www.w3.org/TR/2011/WD-html5-20110405/forms.html#the-label-element) labels are "associated with a specific form control" so whilst it's not invalid to have multiple interactive descendants of a label, it's not the intention. MDN [covers buttons too](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#accessibility_concerns). 

If it's relevant too, [the next major version of this component](https://github.com/i-like-robots/react-tag-autocomplete) includes a label element.
