### ISSUE TITLE
Support React 18

### ISSUE THREAD

**Issue by muyiwaoyeniyi** [i-like-robots/react-tags#267]
Thanks a lot for this package! Please are you able to add support for React 18?

**Comment by i-like-robots** [comment]
The [next major version](https://github.com/i-like-robots/react-tag-autocomplete/) of the component - which is currently in beta - already supports react 18.

I don't think many changes would be required to support React 18 it in the current version but I'd likely have to rewrite the test suite to ensure compatibility, I really don't fancy that!

**Comment by muyiwaoyeniyi** [comment]
@i-like-robots Thanks for the note. I will check out the new version in beta and provide feedback if I run into any issues. Thanks a lot!

**Comment by i-like-robots** [comment]
Closing as v7 has now been released.
