### ISSUE TITLE
Idea - Fix Types - Tag Id can be null ( In case allowNew: true )

### ISSUE THREAD

**Issue by rusikf** [i-like-robots/react-tags#268]
## Expected behaviour

```ts
export interface Tag {
    id: string | number | null;
    name: string;
    disabled?: boolean | undefined;
}
```

## Current behavior

The tag cannot be null. But it's possible if you add a new tag with `allowNew: true` option. Of course, you can add a fake id inside  `onAddition` for it, but it will be useful to distinguish between new and existing tags.

## Additional context

[Link to types.](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-tag-autocomplete/index.d.ts#L15)

**Comment by i-like-robots** [comment]
Thanks for the report but I'm afraid the type definitions you linked to are not maintained by me and I'm not aware they're associated with anybody who has helped me to maintain it either. 

The [next major version](https://github.com/i-like-robots/react-tag-autocomplete/) of the component has been authored in TypeScript so includes its own type definitions. That's currently in beta and I plan to release it fully quite soon.

**Comment by rusikf** [comment]
Thank's for the fast response and clarification! :+1:
