### ISSUE TITLE
Can't Select Suggestion when input cut-off top of screen. (Mi Tab) specific.

### ISSUE THREAD

**Issue by poonam-tru** [i-like-robots/react-tags#274]
Your issue may already be reported! Please search on the [issue tracker](../) before creating one.

## Expected behaviour

I want to add selected suggestion in box when input is behind the window screen.

## Current behaviour

When input field is behind the window screen and input visibility is cutting off in small screen , On click from suggestion box, first come to focus the input and after then i need to again select the item to add it.

## Steps to Reproduce

Steps to reproduce the problem:

1. Scroll up the input field top of the screen and its showing half of the input
2. Select suggestion, it will firstly focus to input, and not selecting the field
3. I need to again click on the suggestion

## Example and screenshots
<img width="876" alt="Screenshot 2023-01-10 at 4 19 51 PM" src="https://user-images.githubusercontent.com/59247001/211531930-dff9e231-d875-4a0c-9b5c-d3ec050fb9bb.png">

When my input is out of screen and i am trying ti select suggestion, It move me to scrollintoView and not selecting suggestions.

## Your environment

 - OS: Catalina
 - Browser: Chrome, safari, mozilla
 - Version of the component: beta
 - React version: 16

**Comment by poonam-tru** [comment]
Hi,
Thanks for the reply.
I have generated a video with the link attached below. When my input is out
of screen and not visible. I am unable to select the suggestion in one
click. It's first scrolled down and I have to click once again to select.

https://www.awesomescreenshot.com/video/13955894?key=41e04ad8a657922385ce8bbb9c919426

**Comment by i-like-robots** [comment]
Thank you for the video @poonam-tru, following this I have been able to re-create the issue in both Chrome and Safari on MacOS. The issue does not seem to be present in Firefox on MacOS nor Safari on iOS. I will continue to test with further browsers and devices.

**Comment by poonam-tru** [comment]
Great, thanks for letting me know.

**Comment by i-like-robots** [comment]
I've now been able to diagnose the issue. There is a blur event listener on the input that forces focus to return to it when a user interacts with the combobox. This is forcing the document to scroll to the focussed input and this is happening before the click event on the option.

To resolve I can either refactor the focus handling a little or use the [prevent scroll option](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#parameters).

**Comment by i-like-robots** [comment]
Closing in favour of https://github.com/i-like-robots/react-tag-autocomplete/issues/30

**Comment by poonam-tru** [comment]
Thanks, I'll check it out.

**Comment by poonam-tru** [comment]
@i-like-robots , I have implemented the same as you mentioned. Its working nicely on the desktop browsers. But It create problem in the mi tab. The same issue I have faced in the Mi Tab Chrome. Can you please try to regenerate it?
