### ISSUE TITLE
Clicking on the last tag removes all of them, does it suppose to be like that?

### ISSUE THREAD

**Issue by DvirH** [i-like-robots/react-tags#35]
I just added tag (3 tags for example), and click on the last tag. It removed all the tags at once.
If I'll click on the first one it will be fine.

**Comment by i-like-robots** [comment]
Thanks for the report @DvirH - I haven't yet been able to re-create the issue (I've tried with the `allowNew` flag both on and off). Would you be able to provide more information about the steps required to see this bug?

**Comment by DvirH** [comment]
I'm using the example-code as provided :)
Actually it seems like the delete handle event called twice from some reason even when I click on single tag, but I can't figure why. There is not event on my own on the top of it. I'll try to play it around and see if there are some founds :+1: 

`handleDelete(i) {        
        var tags = this.state.genes
        tags.splice(i, 1)
        this.setState({ genes: tags })
        this.updateParent('genes', tags, this.props.name)
    }

    handleAddition(tag) {
        var tags = this.state.genes
        tags.push(tag)
        this.setState({ genes: tags })
        this.updateParent('genes', tags, this.props.name)
    }`

**Comment by i-like-robots** [comment]
In your `handleDelete` callback the `splice` function is only ever going to remove one item, so even if it was called twice it would not remove more than one item. If you're able to create a standalone demo of your integration I'm happy to spend a few minutes investigating.

**Comment by DvirH** [comment]
Ok, I find out that there is label(disaply:block) wrapping the `ReactTags` element, and what cause the problem. I'll try to see why

 ```
<div className="form-control-default">
                    <label>
                        <p>Text Here</p>
                        <ReactTags
                            tags={this.state.features}
                            suggestions={this.state.featuresSuggestions}
                            handleDelete={this.featuresHandleDelete}
                            handleAddition={this.featuresHandleAddition}
                            handleInputChange={this.featuresHandleSearch}
                            placeholder="Add Feature" />
                    </label>
                </div>
```

**Comment by DvirH** [comment]
Haha Funny, But It seems the label which wrapped the element behave like default `for` attribute and clicked buttons randomly.  I just added htmlFor="" to solve the problem :)

**Comment by i-like-robots** [comment]
Ahh, yes each tag is a button. The label can become a control for any of the interactive elements inside. I'd recommend not wrapping the component inside a label as they're only intended to label a single interactive element ( [the spec](https://www.w3.org/TR/html5/forms.html#the-label-element)).
