### ISSUE TITLE
Adding a new tag entered by a click on another component.

### ISSUE THREAD

**Issue by magician11** [i-like-robots/react-tags#40]
Let's say I want to have another button/icon that when clicked adds a tag that is being entered in this component.

What's the cleanest way to do that?

I'll want to update the state of tags, as well as clear the input text entered. I haven't worked out how to do the latter yet.

Thanks.

**Comment by i-like-robots** [comment]
The first is easy - your component that integrates this one is in full control of the currently selected tags.

The second... requires burying into the internals which is risky because things may change. I don't know how much utility there is in creating a public interface for it. However, it can be done:

```js
class MyComponent extends React.Component {

  constructor () {
    super()
    this.state = { tags: [] }
  }

  onClick () {
    // add your tag...
    this.setState({ tags: [...this.state.tags, { id: 123, name: 'My new tag' }]

    // clear the input...
    this.autocomplete.input.input.value = ''

    // and trigger a change
    this.autocomplete.input.input.dispatchEvent(new Event('change', { bubbles: true }))
  }

  render () {
    <ReactTags ref={(c) => { this.autocomplete = c }} tags={this.state.tags} />
    <button onClick={this.onClick.bind(this)}>Add a tag!</button>
  }

}
```

**Comment by magician11** [comment]
Thanks @i-like-robots 

Also, I've been wondering what the purpose of having an id with a tag name is?

**Comment by i-like-robots** [comment]
> Also, I've been wondering what the purpose of having an id with a tag name is?

One of the reasons for forking from the original component was because we were working with a metadata system and each tag has a UUID and tags and content are associated with it. The ID field can be left blank if you don't need it.

> My team wants the focus to be set in the input box after an item is selected from the dropdown, with not just tab and enter, but clicks too. It seems from your code, that this should be behaving this way?

No... but it could be altered if you or your team wishes to submit a PR. Because by default the autoresizing text input is presented without a border it's not clear where somebody should click to focus it so this was intended to catch those ambiguous clicks.

**Comment by magician11** [comment]
Maybe what I should have said, is once a tag is added, by clicking on an item in the dropdown or using the keypad, to put the focus in the input box. I'm not sure if your answer above addressed this?

Thanks for clarifying the id q.

**Comment by magician11** [comment]
I tried adding `this.input.input.focus()` after [here](https://github.com/i-like-robots/react-tags/blob/master/lib/ReactTags.js#L129) to ensure that the focus gets put back into the input after an item in the dropdown is selected. But it doesn't seem to add the cursor back there.

Any idea why @i-like-robots ?

**Comment by i-like-robots** [comment]
It may be because the `addTag` callback is triggered on `mousedown` and the browser will move the cursor _after_ this event. I can't test this right now but perhaps switching to a click event will enable you to programatically change the focussed element.

**Comment by magician11** [comment]
I tried a few different approaches to get this going...

**1.**

For some reason, the `onClick` event is not being fired when attached to the `li` element in the `Suggestions` component. If I change the mouse event to something like `onMouseOver` it works fine. But this doesn't solve the issue here though.

**2.**

I thought of using the `componentDidUpdate` method to set the focus.

````
  componentDidUpdate () {
    this.input.input.focus();
  }
````

This works. But I don't always want it to set the focus. I tried doing it conditionally

````
  componentDidUpdate () {
    if(this.state.focused) {
      this.input.input.focus();
    }
  }
````

But this is not working. As I'm setting `focused` to `true` in the `addTag` function, but the `handleBlur` function is being called after it, thereby setting it to `false`.

**3.**

Lastly I tried to attach a reference to the `ReactTags` component.

````
<ReactTags
            ref={ref => this.reactTags = ref}
````

and then somewhere in my code going `this.reactTags.input.input.focus();`. But for some reason this is not working either.

**Comment by i-like-robots** [comment]
I'll have a look into this - it looks like the suggestion cannot currently be clicked because the list is hidden before the `mouseup` event is triggered (a `click` event is a `mousedown` and `mouseup` occurring on the same element). It should be a simple solution... fingers crossed.

**Comment by magician11** [comment]
Nice solution. Thanks @i-like-robots
