### ISSUE TITLE
Language support

### ISSUE THREAD

**Issue by VladmirZhdanov1992** [i-like-robots/react-tags#41]
There is one problem. Hints do not work for Cyrillic
I will be happy if you add support for anothers languages

**Comment by i-like-robots** [comment]
I'm afraid I'm not sure what your are referring to - what `hints` do you mean? Would you be able to setup an example?

**Comment by VladmirZhdanov1992** [comment]
I fixed this problem. I did fork and changed `\\b${query}` on `^${query}` (Suggestions.js:15); This helped me^ but i am not sure, that this is normal for another's.
Sorry my english)

**Comment by i-like-robots** [comment]
I think I've got you... I'm tackling a similar problem with another project - the lack of full unicode support in JS regexps is hard!

**Comment by i-like-robots** [comment]
For reference, the word boundary does not work because cyrillic text - like many unicode characters - is not recognised as a word character. E.G.:

```js
/\b(\w)/.exec('Þingvellir').pop() // 'i'
/\b(\w)/.exec('Thingvellir').pop() // 'T'
```

**Comment by i-like-robots** [comment]
@VladmirZhdanov1992 one of the useful things about using `\b` is that it can match any word in a string rather than just at the start. Could you try the following regexp and see how that works for you?

```
(?:^|\\s)${query}
```

**Comment by VladmirZhdanov1992** [comment]
OK. i try this solution today
