### ISSUE TITLE
error from Backslash 

### ISSUE THREAD

**Issue by footloosemoose** [i-like-robots/react-tags#42]
Hi all – when typing a backslash into the input field, I get the following error:

`Uncaught SyntaxError: Invalid regular expression: /\b\/: \ at end of pattern`

which points to the `var regex...` line below:

```
function filterSuggestions (query, suggestions, length) {
  var regex = new RegExp(("\\b" + query), 'i')
  return suggestions.filter(function (item) { return regex.test(item.name); }).slice(0, length)
}
```

Is this a known issue? Is there an existing way to deal with this?  I can't see how to hook into the onChange event to add additional input filters. 

Any advice/help most welcome.

Thanks for the cool component.

**Comment by i-like-robots** [comment]
Thanks for reporting @footloosemoose - yes the query needs escaping in this case. There's no way to hook in right now but I think this should be a standard feature. Something like this could be implemented:

```js
query.replace(/[-\\^$*+?.()|[\]{}]/g, "\\$&")
```
