### ISSUE TITLE
Use name other than "id" or "name"

### ISSUE THREAD

**Issue by yarnball** [i-like-robots/react-tags#45]
Hi,

I would like to use the following JSON data for my suggestions field. I am accessing it via a fetch.

I have been able to get the tags to appear for each json object- but no text name/titles appear. I'd also only like to use the tags within "tags".

So this data:
[{
        "title": "Citizen Cain",
        "tag": [
            {
                "name": "Movie",
                "taglevel": 1,
                "id": 1
            },
            {
                "name": "Classic",
                "taglevel": 2,
                "id": 4
            }
        ],
        "info": []
    },
        {
        "title": "Anne Hall",
        "tag": [
            {
                "name": "Movie",
                "taglevel": 1,
                "id": 1
            },
            {
                "name": "Indie",
                "taglevel": 2,
                "id": 31
            }
        ],
        "info": []
}]

**Comment by i-like-robots** [comment]
@yarnball You'll need to transform the data before passing it down to this component. If you loop over your data set, concatenate the `tag` fields into a new array and then remove duplicates that should work =]

**Comment by yarnball** [comment]
Thank you for the reply. I am unsure how to transform the data before passing it unfortunately

**Comment by i-like-robots** [comment]
You need to create an empty array then loop over each item in your response, check if it has a `tag` property, append it to your new array and de-dupe.

```js
fetch(...).then(data => {

  // concatenate tags - method 1
  var tags = []
  data.forEach(item => Array.isArray(item.tag) && tags.push.apply(tags, item.tag))

  // concatenate tags  - method 2
  var tags = data.reduce((arr, item) => Array.isArray(item.tag) ? arr.concat(item.tag) : arr, [])

  return dedupe(tags)
})
```

I'm sure you can finish it =]
