### ISSUE TITLE
"Warning: Unknown prop `autoresize` on <input> tag.

### ISSUE THREAD

**Issue by cnkrishna** [i-like-robots/react-tags#48]
Hello,

  We are using react-tag-autocomplete in our project.  We are getting the following warning when launching our component.

"Warning: Unknown prop `autoresize` on <input> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in input (created by exports)
    in div (created by exports)
    in exports (created by exports)
    in div (created by exports)
    in div (created by exports)
    in exports (created by TagElem)
    in TagElem (created by MVMComponent)

We did suppress the property autoresize when we are launching react-tag-autocomplete by using delete props.autoresize.  Looks like autoresize is optional anyway but I think your component should also suppress sending the property to underlying <input>.  Could you please let us know if there is any workaround?  thanks.

**Comment by i-like-robots** [comment]
This was fixed in 8074053c7d41daf5860e79aad2d0ae80eb8ef684 which was shipped as part of the v5 release.

If you need help upgrading from v4 to v5 see the readme here: https://github.com/i-like-robots/react-tags#upgrading-from-4x-to-50
