### ISSUE TITLE
Disable highlighting

### ISSUE THREAD

**Issue by vijayst** [i-like-robots/react-tags#49]
I want to disable highlighting in the AutoSuggest box. It will be convenient to do it via prop.

**Comment by i-like-robots** [comment]
Are referring to the border around the component when the input has focus or the list of suggestions when one is highlighted?

Either way you can adjust the styles with CSS:

- https://github.com/i-like-robots/react-tags/blob/master/example/styles.css#L39-L41
- https://github.com/i-like-robots/react-tags/blob/master/example/styles.css#L152-L154

**Comment by vijayst** [comment]
What I want is the underline of the search text to be removed. When "Spen" is searched for, I get Spencers2. The "Spen" is highlighted with an underline. I want the underline to be removed.

![screen shot 2016-10-07 at 11 00 05 am](https://cloud.githubusercontent.com/assets/3457565/19179662/903ccb2a-8c7d-11e6-9dac-cc9c2cb1e43a.png)

**Comment by vijayst** [comment]
I am able to remove the highlighting with the following style.

```
.react-tags__suggestions li mark {
  /* text-decoration: underline; */
  background: none;
  font-weight: normal; /* 600 */
  margin-right: -2px;
  color: #89949B;
}
```
