### ISSUE TITLE
UMD Build

### ISSUE THREAD

**Issue by souporserious** [i-like-robots/react-tags#53]
My work requires a UMD built file. Is there a possibility of adding this to a `dist-amd` folder?

**Comment by i-like-robots** [comment]
Personally I'm not a fan keeping compiled code in the repo... I do so already for projects distributed on Bower and it's a pain! If there is enough interest however, I may add it.

Out of interest, what forces you to use a UMD wrapper?

**Comment by souporserious** [comment]
We work in a rails environment and don't have access to NPM at the moment :/ I built it locally by adding `dist-amd` folder so we can use that for now. I added a prod webpack build. I can PR it in if you would like? We can access it through unpkg.com. I build all my libraries with UMD dist files that don't live in the repo e.g. https://unpkg.com/react-measure/dist/

**Comment by i-like-robots** [comment]
Interesting, I'll check it out. Certainly preferable to bundling compiled code in the repo. If you're happy to submit a PR I'd be very grateful otherwise if you could link me to an example I'll get around to it soon.

**Comment by ajmas** [comment]
One possible alternative is creating the release archives with the dist code already in place?

When I checked the following I didn't see any dist arteifacts: https://github.com/i-like-robots/react-tags/releases

**Comment by i-like-robots** [comment]
I'm afraid the they're only git tags, I haven't been creating or managing any custom zipfiles or tarballs for Github.

However, transpiled assets are created and uploaded to NPM for each release.

I'm going to close this issue for now as I do not have plans to release packages anywhere other than NPM
