### ISSUE TITLE
Preventing characters in a tag?

### ISSUE THREAD

**Issue by growthlabs** [i-like-robots/react-tags#58]
What is the suggested way for preventing unsupported characters from appearing in a tag? For example we don't want to allow commas or spaces, due to expectations of the backend system.

**Comment by i-like-robots** [comment]
You can manipulate the tag in your `handleAddition` callback, E.G.:

```js
function handleAddtion (tag) {
  tag = Obect.assign({}, tag, { name: tag.name.replace(/[^a-z0-9\s]+/, '') })
  this.setState({ tags: this.state.tags.concat(tag) })
}
```
