### ISSUE TITLE
How to prevent duplicate data from showing

### ISSUE THREAD

**Issue by EduardJS** [i-like-robots/react-tags#62]
Hello!

Is there any way to prevent already selected tags from being shown in the suggestions ?

Regards!

**Comment by i-like-robots** [comment]
Usually the component that wraps this one will be providing the suggestions and maintaining the state of the selected tags. With both pieces of information it should be quite simple to filter the suggestions.

```js
class MyComponent extends Component {
  constructor (props) {
    super(props)
    this.state { tags: [] }
  }

  render () {
    const filtered = this.props.suggestions.filter(...)

    return (
      <ReactTags tags={this.state.tags} suggestions={filtered} />
    )
}
```

**Comment by EduardJS** [comment]
Hei! My issue was that I was not receiving suggestions at render time ( but later, since I am working with Firebase ).

And since I would receive data at a later time, i would have to manipulate the data ( in order to have an array which fits ( id, name ). 

I have managed to make it work by using the parent component with a default suggestion state, and pass thr manipulated suggestions down to my component.

Was just wondering if I could deal with the suggestions format under the hood, in your component.

Thanks for the reply though! It took me an hour but it works :).
