### ISSUE TITLE
Multiple closed buttons if 'name' is an element

### ISSUE THREAD

**Issue by ZephD** [i-like-robots/react-tags#65]
if you would like the content of the selected tags to, for example, have an icon:

```
const tags = [
  { name: <div><i className="fa fa-circle" />{'my name here'}</div> }
]
```

The resultant tag has multiple close buttons:

![screenshot from 2017-03-03 15-32-58](https://cloud.githubusercontent.com/assets/1461917/23557087/c0ea1058-0026-11e7-8711-6c5a51206780.png)

**Comment by i-like-robots** [comment]
You can provide a custom tag component using the [`tagComponent`](https://github.com/i-like-robots/react-tags#tagcomponent-optional) option
