### ISSUE TITLE
Why is the index passed as the parameter to handleDelete and not the tag? 

### ISSUE THREAD

**Issue by startswithaj** [i-like-robots/react-tags#67]
If you generate the selected tags at render and do not store them in state, there is no way to see which tag was deleted. It should call handleDelete with the tag. You can then get the index of the deleted by going tags.index(tag) if you needed the index for whatever reason.

**Comment by i-like-robots** [comment]
This component is based on a parent project that works in this way and I've not yet had the need to change it. The readme and example both display how best to integrate this component.

If you're unhappy with it you're free to fork it and change it as you wish, just as I did from the original.
