### ISSUE TITLE
Can't enter tags unless there are suggestions

### ISSUE THREAD

**Issue by tomkiss** [i-like-robots/react-tags#68]
Hello!

Hope fully i'm not being a numnuts here -

The documentation says that the suggestions are optional. However, when I leave the suggestions parameter as empty [], and try to submit a tag, nothing happens. Pressing enter does not submit the form to add the word I've just typed as a tag.

Am I missing something?

**Comment by i-like-robots** [comment]
By default the `allowNew` option is false (meaning you may only pick from the suggested tags), https://github.com/i-like-robots/react-tags#allowNew

**Comment by tomkiss** [comment]
Aha! Thank you so much 👍
