### ISSUE TITLE
Warning: Accessing PropTypes via the main React package is deprecated.

### ISSUE THREAD

**Issue by oolleegg55** [i-like-robots/react-tags#70]
Hello. 
New version of React (15.5.0) throws the warning: Warning: Accessing PropTypes via the main React package is deprecated.

This is mentioned in their blog: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html

**Comment by i-like-robots** [comment]
Thanks for the heads up @oolleegg55
