### ISSUE TITLE
ReactTags with Preact 8.x

### ISSUE THREAD

**Issue by Londeren** [i-like-robots/react-tags#75]
Howdy!
I've tried to use ReactTags with Preact, but this is not working well. Is it possible to make a quick fix for it?

Sandbox: https://jsfiddle.net/londeren/bd52oyqq/

**Comment by i-like-robots** [comment]
Thanks for the report @Londeren. Have you managed to track down any reasons why this may have broken?

**Comment by Londeren** [comment]
Event bindings
`onBlur
onFocus
onChange
onKeyDown`
don't work on `div`. I've moved them to `Input`. And it seems everything worked correctly.

**Comment by i-like-robots** [comment]
Thanks for checking - that sounds like it may be a regression or change in behaviour from https://github.com/developit/preact/pull/271. From a quick glance it appears as though Preact now expects the attributes to be named `onFocusCapture` and `onChangeCapture`.
