### ISSUE TITLE
Delimiters - Any workarounds?

### ISSUE THREAD

**Issue by markus101** [i-like-robots/react-tags#76]
I see that being able to specify delimiters was removed in v5, is there a work around to that? My use-case requires a comma and a space to create a new tag to as I'm replacing an existing component with that behaviour.

Is there an alternative or workaround to achieve the the behaviour we're looking for?

**Comment by i-like-robots** [comment]
I'm afraid I can't think of a workaround @markus101, perhaps it should be brought back?

**Comment by markus101** [comment]
If you're open to it, it'd definitely help out in my scenario.

Was there a particular reason why it was removed?

**Comment by i-like-robots** [comment]
Yep - I think it's fine to bring back. I can't remember exactly why I took it out, probably just so it was less code to try and maintain.

If you're up for making a PR that would be great, I don't have much time right now.

**Comment by markus101** [comment]
Thanks! I'll put together a PR that.

**Comment by Pomax** [comment]
@markus101 any luck on that PR? We also have a form that uses the autocomplete component and needing to type "enter" in a single-line text input field is quite the anti-pattern, no one's going to guess that key =)

**Comment by markus101** [comment]
I got it mostly done then sidetracked by vacation and some other work, I should have it done soon™.

**Comment by Pomax** [comment]
Since I'm looking at making this work atm in our codebase, I figured I'd file a quick PR to add a `delimiters` prop to the component again.

**Comment by Pomax** [comment]
as a workaround for people who find this issue before it's fixed, I'm currently hooking into the ReactTags component during `componentDidMount` (using a ref function that binds the object as `this.reactTags`), faking ENTER when a comma is seen:
```
      const reactTags = this.reactTags;
      const trueInput = reactTags.input.input;
      const forceKey = reactTags.handleKeyDown.bind(reactTags);
 
      trueInput.addEventListener("keyup", evt => {
        // did we type a comma?
        const key = evt.key;
        if (key === ',') {
          // remove the comma and type an enter instead
          const { query, selectedIndex } = reactTags.state;
          reactTags.state.query = query.substring(0, query.length-1);
          forceKey({ keyCode: 13, preventDefault: ()=>{} });
        }
```
This of course relies specific on the current version of the code, so use this hack at your own risk.
