### ISSUE TITLE
insert checkbox

### ISSUE THREAD

**Issue by mandelaloko** [i-like-robots/react-tags#78]
I am customizing the tags, once finished I will give a pull request.
Examples:
![captura de tela 2017-05-18 as 09 36 22](https://cloud.githubusercontent.com/assets/13973499/26202415/c0b602fa-3bad-11e7-8a43-1a67eee1b750.png)
![captura de tela 2017-05-18 as 09 36 29](https://cloud.githubusercontent.com/assets/13973499/26202419/c5090302-3bad-11e7-9213-f2f1eba30698.png)

**Comment by i-like-robots** [comment]
Interesting, what's the use-case @mandelaloko? It's possible to pass in your own tag component with the [`tagComponent`](https://github.com/i-like-robots/react-tags#tagComponent) option so not sure this is a core-lib feature but I'd be keen to see the result 😄

**Comment by mandelaloko** [comment]
I'm making an app for a restaurant and I need to tell which products are top of the line or something, so I've put that option in the tags.
I've already put value and text fields.
![captura de tela 2017-05-22 as 10 39 10](https://cloud.githubusercontent.com/assets/13973499/26311620/58154ec8-3edb-11e7-9c7c-14821731f5de.png)
![captura de tela 2017-05-22 as 10 39 03](https://cloud.githubusercontent.com/assets/13973499/26311626/5dad0e48-3edb-11e7-8c09-752308360eb7.png)

Sorry, my english, I'm using google translator.
