### ISSUE TITLE
Custom filtering function

### ISSUE THREAD

**Issue by ezakto** [i-like-robots/react-tags#82]
Would be a great feature to allow customizing the filtering function.
The current function looks for matches at the beginning of each word (^|\s), but in my case I needed to use word boundaries (^|\b). And I think another common case would be implementing fuzzy search. So, providing a filteringFunction prop to override the default func would be nice!

**Comment by i-like-robots** [comment]
Hi @ezakto - that's a nice suggestion. Just do you know, the component used to a use word boundaries regex but that caused issues with non-ascii characters! See https://github.com/i-like-robots/react-tags/issues/41 for details.

**Comment by ezakto** [comment]
@i-like-robots Yeah, js regexps are not really good handling unicode. But different use cases could be solved with other kind of filtering methods other than regexp, right?

**Comment by i-like-robots** [comment]
Added `suggestionsFilter` option in #153
