### ISSUE TITLE
【Question】Is there any easy way to show optional variable in Suggestions component ?

### ISSUE THREAD

**Issue by KohheePeace** [i-like-robots/react-tags#85]
Hi. Really thanks for great job : )

I want to show the "tag's counts" in suggest component like medium. 

Is there any easy way to do this?? 

![2017-07-31 21 21 11](https://user-images.githubusercontent.com/29557494/28779584-42f0899e-7636-11e7-9fa6-10f92b37697b.png)

**Comment by i-like-robots** [comment]
We used to do this exact thing with it - but the count was simply appended to the tag name, it was not styled differently. It would be possibly add a prop to provide a custom suggestion component as we do for the selected tags.

**Comment by KohheePeace** [comment]
Thanks for your advice :) I'll try it.
