### ISSUE TITLE
Allow customizing 'Click to remove tag' text

### ISSUE THREAD

**Issue by zdila** [i-like-robots/react-tags#86]
Please allow customizing _Click to remove tag_ text.

**Comment by i-like-robots** [comment]
Hi @zdila it's currently possible to supply a custom selected tag component using the `tagComponent` option, does that work for you? If not I'd be happy to consider a pull request 🙂

**Comment by zdila** [comment]
Thanks, using custom tag component is OK. You may close the issue :-)
