### ISSUE TITLE
Convert user specified event handlers to React naming conventions

### ISSUE THREAD

**Issue by ajmas** [i-like-robots/react-tags#91]
Currently we are allowing the users of react-tags to specify the following event over-ride handlers:

  - handleDelete
  - handleAddition
  - handleInputChange
  - handlePaste

React would expect the to start with 'on', such that:

  - onDelete
  - onAddition
  - onInputChange
  - onPaste

To bring react-tags in line with conventions it would be good to update these. At the same time, a change here would likely break existing code, therefore the evolution should be:

   - Add the new events, deprecating the current ones, in a minor release
   - Remove the current ones, in a major release

**Comment by i-like-robots** [comment]
I'm indifferent about this to be honest. I have no qualms about seeing the change as part of the next major release but I have no enthusiasm to maintain a deprecation process for an unwritten convention.

For reference the properties have kept the names used by the component this repo was originally forked from, they're for event handlers so I can see the logic there.
